import "../styles/globals.css";
import Header from "../components/header/Header";
import { Web3ReactProvider } from "@web3-react/core";
import Web3 from "web3";
import Head from "next/head";
import { WalletProvider } from "../context/wallet";
import { createTheme, ThemeProvider } from '@mui/material/styles';
function getLibrary(provider) {
  return new Web3(provider);
}

const THEME = createTheme({
  typography: {
   "fontFamily": `"Poppins"`,
   "fontSize": 14,
   "fontWeightLight": 600,
   "fontWeightRegular": 400,
   "fontWeightMedium": 500
  },
  palette: {
    primary: {
      main: '#7924FF',
    },
    secondary: {
      main: '#1F1927',
    },
  },
});

function MyApp({ Component, pageProps }) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <WalletProvider>
        <ThemeProvider theme={THEME}>
        <Head>
          <title>Hypex</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
            rel="stylesheet"
          />
        </Head>
        <Header />
        <Component {...pageProps} />
        </ThemeProvider>
      </WalletProvider>
    </Web3ReactProvider>
  );
}

export default MyApp;
