import "../styles/globals.css";
import Header from "../components/header/Header";
import { Web3ReactProvider } from "@web3-react/core";
import Web3 from "web3";
import Head from "next/head";
import { WalletProvider } from "../context/wallet";

function getLibrary(provider) {
  return new Web3(provider);
}

function MyApp({ Component, pageProps }) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <WalletProvider>
        <Head>
          <title>Hypex</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
            rel="stylesheet"
          />
        </Head>
        <Header />
        <Component {...pageProps} />
      </WalletProvider>
    </Web3ReactProvider>
  );
}

export default MyApp;
